# Generated by Django 3.1.5 on 2021-03-02 09:36

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudyActionNo', models.CharField(max_length=100, null=True)),
                ('StudyName', models.CharField(max_length=255, null=True)),
                ('Facility', models.CharField(max_length=255, null=True)),
                ('ProjectPhase', models.CharField(max_length=255, null=True)),
                ('Cause', models.TextField(null=True)),
                ('Safeguard', models.TextField(null=True)),
                ('Consequence', models.TextField(null=True)),
                ('Recomendations', models.TextField(null=True)),
                ('InitialRisk', models.CharField(max_length=10, null=True)),
                ('ResidualRisk', models.CharField(max_length=10, null=True)),
                ('Response', models.TextField(null=True)),
                ('Attachment', models.TextField(null=True)),
                ('Organisation', models.CharField(max_length=100, null=True)),
                ('Disipline', models.CharField(max_length=100, null=True)),
                ('Subdisipline', models.CharField(max_length=100, null=True)),
                ('FutureAction', models.TextField(null=True)),
                ('DueDate', models.DateField(auto_now_add=True, null=True)),
                ('QueSeries', models.IntegerField(null=True)),
            ],
            managers=[
                ('myActionItems', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UploadExl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='excelUpload')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
