# Generated by Django 3.1.5 on 2021-01-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadExl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='excelUpload')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
