# Generated by Django 3.1.7 on 2021-05-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitems',
            name='DateCreated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='actionitems',
            name='Revision',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='historicalactionitems',
            name='DateCreated',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalactionitems',
            name='Revision',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
