# Generated by Django 3.1.5 on 2021-01-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadexl',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
