# Generated by Django 3.2.7 on 2021-10-29 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UploadExcel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalactionitems',
            name='ProjectPhase',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='userT.phases'),
        ),
        migrations.AddField(
            model_name='historicalactionitems',
            name='StudyName',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='userT.studies'),
        ),
        migrations.AddField(
            model_name='historicalactionitems',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='Action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UploadExcel.actionitems'),
        ),
        migrations.AddField(
            model_name='attachments',
            name='Action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UploadExcel.actionitems'),
        ),
        migrations.AddField(
            model_name='actionitems',
            name='ProjectPhase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userT.phases'),
        ),
        migrations.AddField(
            model_name='actionitems',
            name='StudyName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userT.studies'),
        ),
        migrations.AddIndex(
            model_name='actionitems',
            index=models.Index(fields=['QueSeries', 'Organisation', 'Disipline', 'Subdisipline'], name='UploadExcel_QueSeri_9f4706_idx'),
        ),
    ]
