<<<<<<< HEAD:UploadExcel/migrations/0002_auto_20210304_1531.py
# Generated by Django 3.1.7 on 2021-03-04 07:31
=======
# Generated by Django 3.1.7 on 2021-03-04 06:07
>>>>>>> 20210304-logout-yhs:UploadExcel/migrations/0002_auto_20210304_1407.py

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='actionitems',
            managers=[
            ],
        ),
    ]
