# Generated by Django 3.1.5 on 2021-06-19 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='Action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UploadExcel.actionitems'),
        ),
    ]
