# Generated by Django 3.1.5 on 2021-07-04 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UploadExcel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalactionitems',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='Action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UploadExcel.actionitems'),
        ),
        migrations.AddField(
            model_name='attachments',
            name='Action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UploadExcel.actionitems'),
        ),
    ]
