# Generated by Django 3.1.5 on 2021-03-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='actionitems',
            managers=[
            ],
        ),
    ]
