# Generated by Django 3.2.7 on 2021-09-22 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0013_phases'),
        ('UploadExcel', '0002_auto_20210901_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitems',
            name='ProjectPhase_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userT.phases'),
        ),
        migrations.AddField(
            model_name='historicalactionitems',
            name='ProjectPhase_FK',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='userT.phases'),
        ),
    ]
