# Generated by Django 3.1.5 on 2021-01-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0002_uploadexl_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudyActionNo', models.CharField(max_length=100)),
                ('StudyName', models.CharField(max_length=255)),
                ('Facility', models.CharField(max_length=255)),
                ('ProjectPhase', models.CharField(max_length=255)),
                ('Cause', models.TextField()),
                ('Consequence', models.TextField()),
                ('Recomendations', models.TextField()),
                ('Organization', models.CharField(max_length=100)),
                ('Disipline', models.CharField(max_length=100)),
                ('Subdisipline', models.CharField(max_length=100)),
                ('FutureAction', models.TextField()),
                ('DueDate', models.DateField(auto_now_add=True, null=True)),
                ('QueSeries', models.IntegerField()),
            ],
        ),
    ]
