# Generated by Django 3.1.5 on 2021-03-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0002_auto_20210303_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionitems',
            old_name='SafeGuard',
            new_name='Safeguard',
        ),
    ]
