# Generated by Django 3.2.7 on 2021-09-22 00:37

from django.db import migrations

def fill_Phases_fk(apps, schema_editor):
  mdlAI = apps.get_model('UploadExcel', 'ActionItems')
  Phases = apps.get_model('userT', 'Phases')
  for actions in mdlAI.objects.all():
    actions.ProjectPhase_FK , created = Phases.objects.get_or_create(ProjectPhase=actions.ProjectPhase)
    actions.save()

class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0003_auto_20210922_0824'),
    ]

    operations = [

        migrations.RunPython(fill_Phases_fk),
    ]
