# Generated by Django 3.1.5 on 2021-09-01 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0012_auto_20210711_1405'),
        ('UploadExcel', '0003_auto_20210902_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitems',
            name='StudyName_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userT.studies'),
        ),
        migrations.AddField(
            model_name='historicalactionitems',
            name='StudyName_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='userT.studies'),
        ),
    ]
