# Generated by Django 3.1.5 on 2021-03-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0003_auto_20210316_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitems',
            name='Attachment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionitems',
            name='Cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionitems',
            name='Consequence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionitems',
            name='Disipline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actionitems',
            name='Facility',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='actionitems',
            name='FutureAction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionitems',
            name='InitialRisk',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='actionitems',
            name='Organisation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actionitems',
            name='ProjectPhase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='actionitems',
            name='QueSeries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionitems',
            name='Recomendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionitems',
            name='ResidualRisk',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='actionitems',
            name='Response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionitems',
            name='Safeguard',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionitems',
            name='StudyActionNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actionitems',
            name='StudyName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='actionitems',
            name='Subdisipline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
