# Generated by Django 3.1.5 on 2021-01-20 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0003_actionitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionitems',
            name='Consequence',
        ),
        migrations.RemoveField(
            model_name='actionitems',
            name='Disipline',
        ),
        migrations.RemoveField(
            model_name='actionitems',
            name='DueDate',
        ),
        migrations.RemoveField(
            model_name='actionitems',
            name='Facility',
        ),
        migrations.RemoveField(
            model_name='actionitems',
            name='FutureAction',
        ),
        migrations.RemoveField(
            model_name='actionitems',
            name='Organization',
        ),
        migrations.RemoveField(
            model_name='actionitems',
            name='ProjectPhase',
        ),
        migrations.RemoveField(
            model_name='actionitems',
            name='QueSeries',
        ),
        migrations.RemoveField(
            model_name='actionitems',
            name='Recomendations',
        ),
        migrations.RemoveField(
            model_name='actionitems',
            name='StudyActionNo',
        ),
        migrations.RemoveField(
            model_name='actionitems',
            name='StudyName',
        ),
        migrations.RemoveField(
            model_name='actionitems',
            name='Subdisipline',
        ),
    ]
