# Generated by Django 3.1.5 on 2021-01-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0004_auto_20210120_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitems',
            name='Consequence',
            field=models.TextField(null=True),
        ),
    ]
