# Generated by Django 3.1.5 on 2021-03-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0004_auto_20210316_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitems',
            name='Attachment',
            field=models.FileField(blank=True, null=True, upload_to='excelUpload'),
        ),
    ]
