# Generated by Django 3.2.7 on 2021-09-22 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0013_phases'),
        ('UploadExcel', '0004_auto_20210922_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionitems',
            old_name='ProjectPhase',
            new_name='ProjectPhase_backup'
        ),
        migrations.RenameField(
            model_name='historicalactionitems',
            old_name='ProjectPhase',
            new_name='ProjectPhase_backup'
        ),
        
        migrations.RenameField(
            model_name='actionitems',
            old_name='ProjectPhase_FK',
            new_name = 'ProjectPhase'
           
        ),
        migrations.RenameField(
            model_name='historicalactionitems',
            old_name='ProjectPhase_FK',
            new_name='ProjectPhase'
        ),
    ]
