# Generated by Django 3.1.5 on 2021-01-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0005_actionitems_consequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitems',
            name='FutureAction',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actionitems',
            name='Recomendations',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='actionitems',
            name='Cause',
            field=models.TextField(null=True),
        ),
    ]
