# Generated by Django 3.1.5 on 2021-09-01 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0012_auto_20210711_1405'),
        ('UploadExcel', '0005_auto_20210902_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionitems',
            old_name='StudyName',
            new_name='StudyName_backup'
        ),
        migrations.RenameField(
            model_name='historicalactionitems',
            old_name='StudyName',
            new_name='StudyName_backup'
        ),
        
        migrations.RenameField(
            model_name='actionitems',
            old_name='StudyName_fk',
            new_name = 'StudyName'
           
        ),
        migrations.RenameField(
            model_name='historicalactionitems',
            old_name='StudyName_fk',
            new_name='StudyName'
        ),
    ]
