# Generated by Django 3.1.5 on 2021-09-06 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0013_phases'),
        ('UploadExcel', '0006_auto_20210902_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitems',
            name='ProjectPhase_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userT.phases'),
        ),
        migrations.AddField(
            model_name='historicalactionitems',
            name='ProjectPhase_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='userT.phases'),
        ),
    ]
