# Generated by Django 3.2.7 on 2021-09-22 01:42

from django.db import migrations


def fill_studies_fk(apps, schema_editor):
  mdlAI = apps.get_model('UploadExcel', 'ActionItems')
  Studies = apps.get_model('userT', 'Studies')
  for actions in mdlAI.objects.all():
    actions.StudyName_fk, created = Studies.objects.get_or_create(StudyName=actions.StudyName)
    actions.save()

class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0006_auto_20210922_0938'),
    ]

    operations = [

         migrations.RunPython(fill_studies_fk),
    ]
