# Generated by Django 3.1.5 on 2021-01-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0006_auto_20210122_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitems',
            name='Disipline',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actionitems',
            name='DueDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='actionitems',
            name='Facility',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='actionitems',
            name='Organization',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actionitems',
            name='ProjectPhase',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='actionitems',
            name='QueSeries',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='actionitems',
            name='StudyActionNo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actionitems',
            name='StudyName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='actionitems',
            name='Subdisipline',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
