# Generated by Django 3.1.5 on 2021-09-06 22:26

from django.db import migrations

def fill_Phases_fk(apps, schema_editor):
  mdlAI = apps.get_model('UploadExcel', 'ActionItems')
  Phases = apps.get_model('userT', 'Phases')
  for actions in mdlAI.objects.all():
    actions.ProjectPhase_fk , created = Phases.objects.get_or_create(ProjectPhase=actions.ProjectPhase)
    actions.save()

class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0007_auto_20210907_0623'),
    ]

    operations = [

        migrations.RunPython(fill_Phases_fk),
    ]
