# Generated by Django 3.1.5 on 2021-03-27 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0007_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='action',
            new_name='Action',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='dateadded',
            new_name='DateAdded',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='reason',
            new_name='Reason',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='username',
            new_name='Username',
        ),
    ]
