# Generated by Django 3.2.7 on 2021-09-22 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0013_phases'),
        ('UploadExcel', '0007_auto_20210922_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionitems',
            old_name='StudyName',
            new_name='StudyName_backup'
        ),
        migrations.RenameField(
            model_name='historicalactionitems',
            old_name='StudyName',
            new_name='StudyName_backup'
        ),
        
        migrations.RenameField(
            model_name='actionitems',
            old_name='StudyName_fk',
            new_name = 'StudyName'
           
        ),
        migrations.RenameField(
            model_name='historicalactionitems',
            old_name='StudyName_fk',
            new_name='StudyName'
        ),
    ]
