# Generated by Django 3.1.5 on 2021-03-29 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0008_auto_20210327_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionitems',
            old_name='Recomendations',
            new_name='Recommendations',
        ),
        migrations.AlterField(
            model_name='comments',
            name='Action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='UploadExcel.actionitems'),
        ),
    ]
