# Generated by Django 3.1.5 on 2021-01-24 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0009_auto_20210124_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadexl',
            old_name='file_id',
            new_name='filename',
        ),
    ]
