# Generated by Django 3.1.5 on 2021-03-29 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0009_auto_20210330_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionitems',
            name='Attachment',
        ),
        migrations.RemoveField(
            model_name='actionitems',
            name='Comments',
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=255, null=True)),
                ('Attachment', models.FileField(blank=True, null=True, upload_to='excelUpload')),
                ('DateAdded', models.DateTimeField(auto_now_add=True)),
                ('Action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Attachment', to='UploadExcel.actionitems')),
            ],
            options={
                'verbose_name_plural': 'Attachments',
            },
        ),
    ]
