# Generated by Django 3.2.7 on 2021-12-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0009_actionitems_uploadexcel_queseri_9f4706_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitems',
            name='MitigativeSafeguard',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionitems',
            name='NodeDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionitems',
            name='PreventiveSafeguard',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalactionitems',
            name='MitigativeSafeguard',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalactionitems',
            name='NodeDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalactionitems',
            name='PreventiveSafeguard',
            field=models.TextField(blank=True, null=True),
        ),
    ]
