# Generated by Django 3.1.5 on 2021-10-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0009_auto_20210908_0645'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='actionitems',
            index=models.Index(fields=['QueSeries', 'Organisation', 'Disipline', 'Subdisipline'], name='UploadExcel_QueSeri_9f4706_idx'),
        ),
    ]
