# Generated by Django 3.2.7 on 2021-12-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0010_auto_20211223_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitems',
            name='NodeNo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='historicalactionitems',
            name='NodeNo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
