# Generated by Django 3.1.5 on 2021-04-05 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0010_auto_20210330_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitems',
            name='QueSeries',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='Action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Attachments', to='UploadExcel.actionitems'),
        ),
    ]
