# Generated by Django 3.1.5 on 2021-01-29 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0011_auto_20210128_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionitems',
            old_name='Organization',
            new_name='organisation',
        ),
    ]
