# Generated by Django 3.1.5 on 2021-04-05 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0011_auto_20210406_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='Action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UploadExcel.actionitems'),
        ),
    ]
