# Generated by Django 4.0.3 on 2022-07-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0011_auto_20220102_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitems',
            name='Signatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalactionitems',
            name='Signatory',
            field=models.BooleanField(default=False),
        ),
    ]
