# Generated by Django 3.1.5 on 2021-02-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0012_auto_20210130_0745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionitems',
            old_name='organisation',
            new_name='Organisation',
        ),
        migrations.RemoveField(
            model_name='uploadexl',
            name='activated',
        ),
    ]
