# Generated by Django 3.1.5 on 2021-02-13 23:32

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0013_auto_20210208_0121'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='actionitems',
            managers=[
                ('ActioneeItems', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='actionitems',
            name='InitialRisk',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='actionitems',
            name='ResidualRisk',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
