# Generated by Django 3.1.5 on 2021-04-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0013_auto_20210411_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadexl',
            old_name='uploaded',
            new_name='DateAdded',
        ),
        migrations.RenameField(
            model_name='uploadexl',
            old_name='filename',
            new_name='Filename',
        ),
        migrations.AddField(
            model_name='uploadexl',
            name='Username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
