# Generated by Django 3.1.5 on 2021-03-02 09:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0014_auto_20210214_0732'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='actionitems',
            managers=[
                ('myActionItems', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='actionitems',
            name='Safeguard',
            field=models.TextField(null=True),
        ),
    ]
