# Generated by Django 3.1.5 on 2021-04-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0014_auto_20210414_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitems',
            name='Guidewords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
