# Generated by Django 3.1.7 on 2021-04-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0015_actionitems_guidewords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitems',
            name='QueSeries',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
