# Generated by Django 3.1.5 on 2021-03-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0015_auto_20210302_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionitems',
            old_name='Safeguard',
            new_name='Safeguard2',
        ),
    ]
