# Generated by Django 3.1.5 on 2021-03-02 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0016_auto_20210302_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionitems',
            name='Safeguard2',
        ),
    ]
