# Generated by Django 3.1.5 on 2021-04-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0016_auto_20210418_2152'),
        ('UploadExcel', '0016_auto_20210418_2228'),
    ]

    operations = [
    ]
