# Generated by Django 3.1.7 on 2021-04-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0017_merge_20210419_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitems',
            name='QueSeriesTarget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
