# Generated by Django 3.0.12 on 2021-03-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0018_actionitems_safeg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionitems',
            old_name='SafeG',
            new_name='SafeGuard',
        ),
    ]
