# Generated by Django 3.1.7 on 2021-05-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0019_historicalactionitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitems',
            name='Deviation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalactionitems',
            name='Deviation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
