# Generated by Django 3.1.7 on 2021-05-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0019_historicalactionitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitems',
            name='DueDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalactionitems',
            name='DueDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
