# Generated by Django 3.1.7 on 2021-05-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0020_auto_20210522_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitems',
            name='DueDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalactionitems',
            name='DueDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
