# Generated by Django 3.1.7 on 2021-04-23 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0002_tenantawaremodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Tenant.tenantawaremodel')),
                ('name', models.CharField(max_length=200)),
            ],
            bases=('Tenant.tenantawaremodel',),
        ),
    ]
