# Generated by Django 4.0.3 on 2022-07-25 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhasesArch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectPhase', models.CharField(max_length=200, null=True)),
                ('Scheduled', models.CharField(max_length=200, null=True)),
                ('Description', models.CharField(max_length=1000, null=True)),
                ('Default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Phases',
            },
        ),
        migrations.CreateModel(
            name='StudiesArch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudyName', models.CharField(max_length=200, null=True)),
                ('ProjectPhase_backup', models.CharField(blank=True, max_length=200, null=True)),
                ('AttendanceList', models.CharField(blank=True, max_length=200, null=True)),
                ('DateConducted', models.DateField(auto_now_add=True, null=True)),
                ('Form', models.CharField(blank=True, max_length=100, null=True)),
                ('Sendemail', models.BooleanField(default=True)),
                ('ProjectPhase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uArchive.phasesarch')),
            ],
        ),
        migrations.CreateModel(
            name='ActionItemsArch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudyActionNo', models.CharField(blank=True, max_length=100, null=True)),
                ('StudyName_backup', models.CharField(blank=True, max_length=255, null=True)),
                ('Facility', models.CharField(blank=True, max_length=255, null=True)),
                ('ProjectPhase_backup', models.CharField(blank=True, max_length=255, null=True)),
                ('Cause', models.TextField(blank=True, null=True)),
                ('Safeguard', models.TextField(blank=True, null=True)),
                ('Consequence', models.TextField(blank=True, null=True)),
                ('Recommendations', models.TextField(blank=True, null=True)),
                ('InitialRisk', models.CharField(blank=True, max_length=10, null=True)),
                ('ResidualRisk', models.CharField(blank=True, max_length=10, null=True)),
                ('Response', models.TextField(blank=True, null=True)),
                ('Organisation', models.CharField(blank=True, max_length=100, null=True)),
                ('Disipline', models.CharField(blank=True, max_length=100, null=True)),
                ('Subdisipline', models.CharField(blank=True, max_length=100, null=True)),
                ('FutureAction', models.TextField(blank=True, null=True)),
                ('DueDate', models.DateField(blank=True, null=True)),
                ('QueSeries', models.IntegerField(blank=True, default=0, null=True)),
                ('QueSeriesTarget', models.IntegerField(blank=True, default=0, null=True)),
                ('Guidewords', models.TextField(blank=True, null=True)),
                ('Deviation', models.TextField(blank=True, null=True)),
                ('Revision', models.IntegerField(blank=True, default=0, null=True)),
                ('DateCreated', models.DateField(auto_now_add=True, null=True)),
                ('NodeNo', models.IntegerField(blank=True, default=0, null=True)),
                ('NodeDescription', models.TextField(blank=True, null=True)),
                ('PreventiveSafeguard', models.TextField(blank=True, null=True)),
                ('MitigativeSafeguard', models.TextField(blank=True, null=True)),
                ('Signatory', models.BooleanField(default=False)),
                ('ProjectPhase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uArchive.phasesarch')),
                ('StudyName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uArchive.studiesarch')),
            ],
        ),
        migrations.AddIndex(
            model_name='actionitemsarch',
            index=models.Index(fields=['QueSeries', 'Organisation', 'Disipline', 'Subdisipline'], name='uArchive_ac_QueSeri_619536_idx'),
        ),
    ]
