# Generated by Django 4.0.3 on 2022-07-30 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uArchive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phasesarch',
            old_name='Default',
            new_name='DefaultX',
        ),
        migrations.RenameField(
            model_name='phasesarch',
            old_name='Description',
            new_name='DescriptionX',
        ),
    ]
