# Generated by Django 4.0.3 on 2022-07-31 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uArchive', '0002_rename_default_phasesarch_defaultx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phasesarch',
            old_name='DefaultX',
            new_name='Default',
        ),
        migrations.RenameField(
            model_name='phasesarch',
            old_name='DescriptionX',
            new_name='Description',
        ),
    ]
