# Generated by Django 4.0.3 on 2022-07-31 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uArchive', '0003_rename_defaultx_phasesarch_default_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phasesarch',
            old_name='Default',
            new_name='DefaultX',
        ),
        migrations.RenameField(
            model_name='phasesarch',
            old_name='Description',
            new_name='DescriptionX',
        ),
    ]
