# Generated by Django 4.0.3 on 2022-08-09 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uArchive', '0004_rename_default_phasesarch_defaultx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=255, null=True)),
                ('Attachment', models.FileField(blank=True, max_length=500, null=True, upload_to='attachments')),
                ('DateAdded', models.DateTimeField(auto_now_add=True)),
                ('Action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uArchive.actionitemsarch')),
            ],
            options={
                'verbose_name_plural': 'Attachments',
            },
        ),
    ]
