# Generated by Django 4.0.3 on 2022-08-16 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uArchive', '0005_attachments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attachments',
            new_name='AttachmentsArch',
        ),
    ]
