# Generated by Django 3.1.5 on 2021-03-03 00:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fullname', models.CharField(max_length=254, null=True)),
                ('disipline', models.CharField(blank=True, max_length=254, null=True)),
                ('subdisipline', models.CharField(blank=True, max_length=254, null=True)),
                ('organisation', models.CharField(blank=True, max_length=254, null=True)),
                ('designation', models.CharField(blank=True, max_length=254, null=True)),
                ('expiration', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionRoutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organisation', models.CharField(max_length=100, null=True)),
                ('Disipline', models.CharField(max_length=100, null=True)),
                ('Subdisipline', models.CharField(max_length=100, null=True)),
                ('Actionee', models.CharField(max_length=100, null=True)),
                ('Approver1', models.CharField(max_length=100, null=True)),
                ('Approver2', models.CharField(max_length=100, null=True)),
                ('Approver3', models.CharField(max_length=100, null=True)),
                ('Approver4', models.CharField(max_length=100, null=True)),
                ('Approver5', models.CharField(max_length=100, null=True)),
            ],
            managers=[
                ('ActioneeRo', django.db.models.manager.Manager()),
            ],
        ),
    ]
