# Generated by Django 3.2.7 on 2021-10-29 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectPhase', models.CharField(max_length=200, null=True)),
                ('Scheduled', models.CharField(max_length=200, null=True)),
                ('Description', models.CharField(max_length=1000, null=True)),
                ('Default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Phases',
            },
        ),
        migrations.CreateModel(
            name='RiskMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Consequence', models.CharField(blank=True, max_length=20, null=True)),
                ('ConsequenceCategory', models.CharField(blank=True, max_length=100, null=True)),
                ('Likelihood', models.CharField(blank=True, max_length=20, null=True)),
                ('LikelihoodCategory', models.CharField(blank=True, max_length=100, null=True)),
                ('Combined', models.CharField(blank=True, max_length=100, null=True)),
                ('Ranking', models.CharField(blank=True, max_length=100, null=True)),
                ('RiskColour', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'RiskMatrix',
            },
        ),
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudyName', models.CharField(max_length=200, null=True)),
                ('ProjectPhase', models.CharField(max_length=200, null=True)),
                ('AttendanceList', models.CharField(max_length=1000, null=True)),
                ('DateConducted', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Studies',
            },
        ),
        migrations.CreateModel(
            name='ActionRoutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organisation', models.CharField(max_length=100, null=True)),
                ('Disipline', models.CharField(max_length=100, null=True)),
                ('Subdisipline', models.CharField(max_length=100, null=True)),
                ('Actionee', models.CharField(max_length=100, null=True)),
                ('Approver1', models.CharField(blank=True, max_length=100, null=True)),
                ('Approver2', models.CharField(blank=True, max_length=100, null=True)),
                ('Approver3', models.CharField(blank=True, max_length=100, null=True)),
                ('Approver4', models.CharField(blank=True, max_length=100, null=True)),
                ('Approver5', models.CharField(blank=True, max_length=100, null=True)),
                ('Approver6', models.CharField(blank=True, max_length=100, null=True)),
                ('Approver7', models.CharField(blank=True, max_length=100, null=True)),
                ('Approver8', models.CharField(blank=True, max_length=100, null=True)),
                ('Studies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='userT.studies')),
            ],
            options={
                'verbose_name_plural': 'ActionRoutes',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=254, null=True)),
                ('disipline', models.CharField(blank=True, max_length=254, null=True)),
                ('subdisipline', models.CharField(blank=True, max_length=254, null=True)),
                ('organisation', models.CharField(blank=True, max_length=254, null=True)),
                ('designation', models.CharField(blank=True, max_length=254, null=True)),
                ('signature', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(blank=True, default=True, null=True)),
                ('staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
