# Generated by Django 3.1.5 on 2021-04-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Workshops', models.CharField(max_length=100, null=True)),
                ('DateRange', models.DateTimeField(null=True)),
                ('AttendanceList', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
