# Generated by Django 3.1.5 on 2021-02-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organisation', models.CharField(max_length=100, null=True)),
                ('Disipline', models.CharField(max_length=100, null=True)),
                ('Subdisipline', models.CharField(max_length=100, null=True)),
                ('Actionee', models.CharField(max_length=100, null=True)),
                ('Approver1', models.CharField(max_length=100, null=True)),
                ('Approver2', models.CharField(max_length=100, null=True)),
                ('Approver3', models.CharField(max_length=100, null=True)),
                ('Approver4', models.CharField(max_length=100, null=True)),
                ('Approver5', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Routes',
            },
        ),
    ]
