# Generated by Django 3.1.5 on 2021-04-15 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0002_workshops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
    ]
