# Generated by Django 3.1.7 on 2021-06-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0002_riskmatrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
