# Generated by Django 3.1.5 on 2021-02-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0002_routes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Routes',
            new_name='Routes2',
        ),
    ]
