# Generated by Django 3.1.5 on 2021-04-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0003_remove_customuser_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_active',
            new_name='active',
        ),
        migrations.AddField(
            model_name='customuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='staff',
            field=models.BooleanField(default=True),
        ),
    ]
