# Generated by Django 3.1.5 on 2021-07-07 22:29

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0003_auto_20210704_1208'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('mdlSetGetField', django.db.models.manager.Manager()),
            ],
        ),
    ]
