# Generated by Django 3.1.5 on 2021-07-07 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0004_auto_20210708_0629'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
