# Generated by Django 3.1.5 on 2021-07-08 12:28

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0005_auto_20210708_0720'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('mdlSetGetField', django.db.models.manager.Manager()),
            ],
        ),
    ]
