# Generated by Django 3.1.5 on 2021-02-07 13:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0005_auto_20210207_1918'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='actionroutes',
            managers=[
                ('ActioneeRoutes', django.db.models.manager.Manager()),
            ],
        ),
    ]
