# Generated by Django 3.1.5 on 2021-04-17 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0006_auto_20210417_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studies',
            options={'verbose_name_plural': 'Studies'},
        ),
        migrations.AddField(
            model_name='actionroutes',
            name='Studies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='userT.studies'),
        ),
    ]
