# Generated by Django 3.1.5 on 2021-02-07 14:04

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0006_auto_20210207_2159'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='actionroutes',
            managers=[
                ('ActioneeRo', django.db.models.manager.Manager()),
            ],
        ),
    ]
