# Generated by Django 3.1.5 on 2021-02-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0007_auto_20210207_2204'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='actionroutes',
            managers=[
            ],
        ),
    ]
