# Generated by Django 3.1.5 on 2021-07-08 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0008_auto_20210709_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='fullname',
            new_name='username',
        ),
    ]
