# Generated by Django 3.1.5 on 2021-04-17 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0008_auto_20210417_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionroutes',
            options={'verbose_name_plural': 'ActionRoutes'},
        ),
    ]
