# Generated by Django 3.1.5 on 2021-02-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0008_auto_20210207_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRoutesX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organisation', models.CharField(max_length=100, null=True)),
                ('Disipline', models.CharField(max_length=100, null=True)),
                ('Subdisipline', models.CharField(max_length=100, null=True)),
                ('Actionee', models.CharField(max_length=100, null=True)),
                ('Approver1', models.CharField(max_length=100, null=True)),
                ('Approver2', models.CharField(max_length=100, null=True)),
                ('Approver3', models.CharField(max_length=100, null=True)),
                ('Approver4', models.CharField(max_length=100, null=True)),
                ('Approver5', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ActionRoutes',
        ),
    ]
