# Generated by Django 3.1.5 on 2021-04-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0009_auto_20210418_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionroutes',
            name='Approver6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actionroutes',
            name='Approver7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actionroutes',
            name='Approver8',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actionroutes',
            name='Approver1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actionroutes',
            name='Approver2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actionroutes',
            name='Approver3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actionroutes',
            name='Approver4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actionroutes',
            name='Approver5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
