# Generated by Django 3.1.5 on 2021-07-09 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0009_auto_20210709_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='username',
            new_name='fullname',
        ),
    ]
