# Generated by Django 3.1.5 on 2021-02-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0009_auto_20210207_2218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActionRoutesX',
            new_name='ActionRoutes',
        ),
    ]
