# Generated by Django 3.1.7 on 2021-05-05 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0010_auto_20210419_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='active',
            new_name='is_active',
        ),
    ]
