# Generated by Django 3.1.5 on 2021-02-07 17:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0010_auto_20210208_0138'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='actionroutes',
            managers=[
                ('ActioneeRo', django.db.models.manager.Manager()),
            ],
        ),
    ]
