# Generated by Django 3.1.6 on 2021-07-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0010_auto_20210709_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
