# Generated by Django 3.1.7 on 2021-05-05 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0011_auto_20210505_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_active',
            new_name='active',
        ),
    ]
