# Generated by Django 3.1.6 on 2021-07-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0011_auto_20210711_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
