# Generated by Django 3.1.5 on 2021-09-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0012_auto_20210711_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectPhase', models.CharField(max_length=200, null=True)),
                ('Scheduled', models.CharField(max_length=200, null=True)),
                ('Description', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Phases',
            },
        ),
    ]
