# Generated by Django 3.1.7 on 2021-05-08 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0012_auto_20210505_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='active',
            new_name='is_active',
        ),
    ]
