# Generated by Django 3.1.5 on 2021-09-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0013_phases'),
    ]

    operations = [
        migrations.AddField(
            model_name='phases',
            name='Default',
            field=models.BooleanField(default=False),
        ),
    ]
