# Generated by Django 3.1.7 on 2021-05-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0013_auto_20210508_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Consequence', models.CharField(blank=True, max_length=20, null=True)),
                ('Likelihood', models.CharField(blank=True, max_length=20, null=True)),
                ('Combined', models.CharField(blank=True, max_length=100, null=True)),
                ('Ranking', models.CharField(blank=True, max_length=100, null=True)),
                ('Colour', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'RiskMatrix',
            },
        ),
    ]
