# Generated by Django 3.2.7 on 2021-10-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0013_phases'),
    ]

    operations = [
        migrations.AddField(
            model_name='phases',
            name='Default',
            field=models.BooleanField(default=False),
        ),
    ]
