# Generated by Django 3.1.5 on 2021-10-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0014_phases_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionroutes',
            name='ProjectPhase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
