# Generated by Django 3.1.5 on 2021-12-15 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0014_phases_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionroutes',
            name='ProjectPhase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userT.phases'),
        ),
        migrations.AddField(
            model_name='studies',
            name='Form',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='ProjectPhase_backup',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='AttendanceList',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='ProjectPhase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userT.phases'),
        ),
    ]
