# Generated by Django 3.2.7 on 2021-12-02 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0014_phases_default'),
    ]

    operations = [
     
        
        migrations.AlterField(
            model_name='studies',
            name='AttendanceList',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
