# Generated by Django 3.2.7 on 2021-12-02 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0015_auto_20211203_0439'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='studies',
            name='ProjectPhase_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userT.phases'),
        ),
    ]
