# Generated by Django 3.1.5 on 2021-12-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0015_auto_20211216_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studies',
            name='AttendanceList',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='ProjectPhase_backup',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
