# Generated by Django 3.1.5 on 2021-10-31 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0015_actionroutes_projectphase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionroutes',
            name='ProjectPhase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userT.phases'),
        ),
    ]
