# Generated by Django 3.2.7 on 2021-12-02 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0016_auto_20211203_0446'),
    ]

    operations = [

        migrations.RenameField(
            model_name='studies',
            old_name='ProjectPhase',
            new_name = 'ProjectPhase_backup'
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='ProjectPhase_new',
            new_name = 'ProjectPhase'
        ),
        
    ]

