# Generated by Django 3.1.5 on 2021-10-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0016_auto_20211101_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='studies',
            name='Form',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='AttendanceList',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
