# Generated by Django 3.1.5 on 2022-04-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0018_parameters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameters',
            options={},
        ),
        migrations.AddField(
            model_name='customuser',
            name='licensing',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
