# Generated by Django 3.1.5 on 2022-04-02 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0019_auto_20220403_0640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameters',
            options={'verbose_name_plural': 'Parameters'},
        ),
    ]
