# Generated by Django 3.1.5 on 2022-04-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0020_auto_20220403_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Urlhref', models.CharField(blank=True, max_length=200, null=True)),
                ('Icon', models.CharField(blank=True, max_length=200, null=True)),
                ('Namemenu', models.CharField(blank=True, max_length=200, null=True)),
                ('Parentid', models.CharField(blank=True, max_length=200, null=True)),
                ('Licensing', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Menus',
            },
        ),
    ]
