# Generated by Django 4.0.3 on 2022-04-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0021_menus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menus',
            old_name='Licensing',
            new_name='Permissioning',
        ),
        migrations.AddField(
            model_name='menus',
            name='Classelement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='menus',
            name='Hierarchy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menus',
            name='Parentid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
