# Generated by Django 4.0.3 on 2022-04-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0022_rename_licensing_menus_permissioning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='Classelement',
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
    ]
