# Generated by Django 4.0.3 on 2022-07-03 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UploadExcel', '0012_actionitems_signatory_and_more'),
        ('userT', '0023_alter_menus_classelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signatory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('designation', models.CharField(blank=True, max_length=254, null=True)),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
                ('route', models.CharField(blank=True, max_length=200, null=True)),
                ('ActionItemsid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UploadExcel.actionitems')),
            ],
        ),
    ]
