# Generated by Django 4.0.3 on 2022-07-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0024_signatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='signatory',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='signatory',
            name='siganture',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
