# Generated by Django 4.0.3 on 2022-07-03 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0025_signatory_name_signatory_siganture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signatory',
            old_name='siganture',
            new_name='signature',
        ),
    ]
