# Generated by Django 4.0.3 on 2022-07-04 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0026_rename_siganture_signatory_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signatory',
            old_name='role',
            new_name='Role',
        ),
        migrations.RenameField(
            model_name='signatory',
            old_name='route',
            new_name='Route',
        ),
        migrations.RenameField(
            model_name='signatory',
            old_name='name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='signatory',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='signatory',
            name='QueSeries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signatory',
            name='Timestamp',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='signatory',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
