# Generated by Django 4.0.3 on 2022-07-04 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0027_rename_role_signatory_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signatory',
            name='Timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
