# Generated by Django 4.0.3 on 2022-07-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0028_alter_signatory_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signatory',
            name='Role',
        ),
        migrations.AddField(
            model_name='signatory',
            name='disipline',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='signatory',
            name='organisation',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='signatory',
            name='subdisipline',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
