# Generated by Django 4.0.3 on 2022-07-05 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0029_remove_signatory_role_signatory_disipline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signatory',
            name='Route',
        ),
    ]
