# Generated by Django 4.0.3 on 2022-07-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userT', '0030_remove_signatory_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='studies',
            name='Sendemail',
            field=models.BooleanField(default=True),
        ),
    ]
