name : Deployment workflow

on: #this line specifies on pull or push test
  pull_request:
  push:
    branches: [ Branch-from-main(deployment-test) ]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: test Get latest code
      uses: actions/checkout@v2

    - name: test Sync files usert
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete --exclude="migrations/" --exclude="__pycache__/" --include="" --filter=""
        path: /userT/
        remote_path: /opt/bitnami/projects/HSETool/userT
        remote_host: 54.255.201.56
        remote_port: 22
        remote_user: bitnami
        remote_key: ${{ secrets.LIGHTSAIL_KEY }}


    - name: test Sync files uploadexcel
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete --exclude="" --include="" --filter=""
        path: /UploadExcel/
        remote_path: /opt/bitnami/projects/HSETool/UploadExcel/
        remote_host: 54.255.201.56
        remote_port: 22
        remote_user: bitnami
        remote_key: ${{ secrets.LIGHTSAIL_KEY }}
      
        
          
