name : Deployment workflow

on: #this line specifies on pull or push
  pull_request:
  push:
    branches: [ Branch-from-main(deployment-test) ]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: test Get latest code
      uses: actions/checkout@v2

    - name: test Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 54.255.201.56
        username: bitnami
        password: ${{ secrets.LIGHTSAIL_KEY }}
        server-dir: /opt/bitnami/projects/HSETool/
        exclude: /opt/bitnami/projects/HSETool/excelUpload
        -/opt/bitnami/projects/HSETool/js
        -/opt/bitnami/projects/HSETool/media
        -/opt/bitnami/projects/HSETool/PDF
        -/opt/bitnami/projects/HSETool/static
        -/opt/bitnami/projects/HSETool/staticfiles
        -/opt/bitnami/projects/HSETool/Tenant
        -/opt/bitnami/projects/HSETool/Trackem

        
          
