name : Django Tests

on:
  push:
    branches:
      -Branch-from-main(deployment-test)

  pull_request:
    branches:
      -Branch-from-main(deployment-test)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.1
      uses: actions/setup-python@v3.9.1
      with:
        python-version: 3.9.1
    -name: Install dependencies
      run: |
        python -m pip install --upgrade pip
# pip install -r requirements.txt
  
