name : Deployment workflow

on: #this line specifies on pull or push
  pull_request:
  push:
    branches: [ Branch-from-main(deployment-test) ]
      
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: testing executing remote ssh commands using password
      uses: appleboy/ssh-action@master #github marketplace app 
      with:
        host: 54.255.201.56
        username: bitnami
        key: ${{ secrets.LIGHTSAIL_KEY }}
        port: 22
        script: |
          cd /opt/bitnami/projects/HSETool/userT
          