name : TESTING Patch for Prism Server

on: #this line specifies on pull or push test
    workflow_dispatch:
      inputs:
        logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
        tags:
          description: 'Test scenario tags'
  
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: test Get latest code
      uses: actions/checkout@v2
# prism instance server
    - name: stop server for test
      uses: appleboy/ssh-action@master #github marketplace app 
      with:
        host: 52.77.81.191
        username: bitnami
        key: ${{ secrets.LIGHTSAIL_KEY }}
        port: 22
        script: |
          sudo /opt/bitnami/ctlscript.sh stop apache

    - name: test Sync files usert views
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete --exclude="" --include="" --filter=""
        path: /userT/views.py
        remote_path: /opt/bitnami/projects/HSETool/userT/views.py
        remote_host: 52.77.81.191
        remote_port: 22
        remote_user: bitnami
        remote_key: ${{ secrets.LIGHTSAIL_KEY }}

    - name: test Sync files usert businesslogic
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete --exclude="" --include="" --filter=""
        path: /userT/businesslogic.py
        remote_path: /opt/bitnami/projects/HSETool/userT/businesslogic.py
        remote_host: 52.77.81.191
        remote_port: 22
        remote_user: bitnami
        remote_key: ${{ secrets.LIGHTSAIL_KEY }}

    - name: test Sync files static Javascript misc.js
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete --exclude="" --include="" --filter=""
        path: /static/Javascript/misc.js
        remote_path: /opt/bitnami/projects/HSETool/static/Javascript/misc.js
        remote_host: 52.77.81.191
        remote_port: 22
        remote_user: bitnami
        remote_key: ${{ secrets.LIGHTSAIL_KEY }}

    - name: test Sync files static generalcss tabsticky.css
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete --exclude="" --include="" --filter=""
        path: /static/generalcss/tabsticky.css
        remote_path: /opt/bitnami/projects/HSETool/generalcss/tabsticky.css
        remote_host: 52.77.81.191
        remote_port: 22
        remote_user: bitnami
        remote_key: ${{ secrets.LIGHTSAIL_KEY }}\

    - name: test Sync files static userT Templates incltopnavbar.html
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete --exclude="" --include="" --filter=""
        path: /userT/Templates/userT/incltopnavbar.html
        remote_path: /opt/bitnami/projects/HSETool/userT/Templates/userT/incltopnavbar.html
        remote_host: 52.77.81.191
        remote_port: 22
        remote_user: bitnami
        remote_key: ${{ secrets.LIGHTSAIL_KEY }}\

    - name: test Sync files static userT Templates reppmtexcel.html
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete --exclude="" --include="" --filter=""
        path: /userT/Templates/userT/reppmtexcel.html
        remote_path: /opt/bitnami/projects/HSETool/userT/Templates/userT/reppmtexcel.html
        remote_host: 52.77.81.191
        remote_port: 22
        remote_user: bitnami
        remote_key: ${{ secrets.LIGHTSAIL_KEY }}

    - name: test Sync files static userT Templates base3.html
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete --exclude="" --include="" --filter=""
        path: /userT/Templates/userT/base3.html
        remote_path: /opt/bitnami/projects/HSETool/userT/Templates/userT/base3.html
        remote_host: 52.77.81.191
        remote_port: 22
        remote_user: bitnami
        remote_key: ${{ secrets.LIGHTSAIL_KEY }}
  
    - name: testing changing user group for SFTP transferred files 
      uses: appleboy/ssh-action@master #github marketplace app 
      with:
        host: 52.77.81.191
        username: bitnami
        key: ${{ secrets.LIGHTSAIL_KEY }}
        port: 22
        script: |
          sudo chgrp -R varwwwusers /opt/bitnami/projects/HSETool/ 
          sudo chmod -R 770 /opt/bitnami/projects/HSETool/
          sudo /opt/bitnami/ctlscript.sh start apache


          
